[build]
publish = "."

[context.production.environment]
# These are just placeholders - actual values are set in Netlify dashboard
NETLIFY_FIREBASE_API_KEY = ""
NETLIFY_FIREBASE_AUTH_DOMAIN = ""
NETLIFY_FIREBASE_DATABASE_URL = ""
NETLIFY_FIREBASE_PROJECT_ID = ""
NETLIFY_FIREBASE_STORAGE_BUCKET = ""
NETLIFY_FIREBASE_MESSAGING_SENDER_ID = ""
NETLIFY_FIREBASE_APP_ID = ""
